language: node_js
node_js:
  - 6
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-atom' ]; then cd .. && eval "mv $currentfolder generator-atom" && cd generator-atom; fi

